module.exports = {
  driver: undefined,
  browser: undefined,
  page: undefined,
  pages: {
    login: undefined,
    posts: undefined,
    pages: undefined,
    tags: undefined,
    members: undefined,
    sidebar: undefined,
    common: undefined,
    editUser: undefined,
  },
  aPrioriDataPool: {},
  pseudoAleatorioDataPool: {
    post: [],
    page: [],
    tag: [],
    member: [],
    user: [],
  },
  actualPseudoAleatorioPosition: {
    post: undefined,
    page: undefined,
    tag: undefined,
    member: undefined,
    user: undefined,
  },
  variables: {},
};
